#!/usr/bin/env bash
code --install-extension 13xforever.language-x86-64-assembly
code --install-extension 2gua.rainbow-brackets
code --install-extension ajshort.include-autocomplete
code --install-extension ajshort.latex-preview
code --install-extension akamud.vscode-theme-onedark
code --install-extension anucecsit.comp2300-extension-pack
code --install-extension anucecsit.comp2300-platformio-ide
code --install-extension austin.code-gnu-global
code --install-extension basdp.language-gas-x86
code --install-extension bbenoist.Doxygen
code --install-extension bltg-team.masm
code --install-extension daltonjorge.scala
code --install-extension dan-c-underwood.arm
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension Gimly81.matlab
code --install-extension HookyQR.beautify
code --install-extension Imanolea.z80-asm
code --install-extension James-Yu.latex-workshop
code --install-extension kdarkhan.mips
code --install-extension Kelvin.vscode-sshfs
code --install-extension lextudio.restructuredtext
code --install-extension maelvalais.autoconf
code --install-extension magicstack.MagicPython
code --install-extension marus25.cortex-debug
code --install-extension mechatroner.rainbow-csv
code --install-extension mitaki28.vscode-clang
code --install-extension ms-python.python
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.powershell
code --install-extension oderwat.indent-rainbow
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension platformio.platformio-ide
code --install-extension redhat.vscode-yaml
code --install-extension ryu1kn.partial-diff
code --install-extension SamuelLampa.theme-cyanicpastels
code --install-extension searKing.preview-vscode
code --install-extension steventattersall.m68k
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tomconte.kickassembler
code --install-extension twxs.cmake
code --install-extension vector-of-bool.cmake-tools
code --install-extension vsciot-vscode.vscode-arduino
code --install-extension vscode-icons-team.vscode-icons
code --install-extension zhuangtongfa.Material-theme
code --install-extension Zignd.html-css-class-completion

