name: Test install script on multiple arch and distro

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-on-arch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: 
          - aarch64
          - armv6
          - armv7
        distro:
          - ubuntu20.04
          - ubuntu22.04
          - stretch
          - buster
          - bullseye
          - alpine_latest
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run command on ${{ matrix.distro }} ${{ matrix.arch }}
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          run: |
            wget -O - https://github.com/protik09/Setup-Scripts/raw/master/raspberrypi/raspi.sh | bash
