name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run the raspberry pi QEMU image and run the test script in the VM
      run: docker run -i -v $HOME/.dockerpi:/sdcard lukechilds/dockerpi
